services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
